backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blogs"
    label: "Blogs"
    files:
      - name: "blogs"
        label: "Blogs List"
        file: "public/content/blogs.json"
        fields:
          - label: "Blogs"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Body", name: "body", widget: "text" }

  - name: "events"
    label: "Events"
    files:
      - name: "events"
        label: "Events List"
        file: "public/content/events.json"
        fields:
          - label: "Events"
            name: "items"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Description", name: "description", widget: "text" }
